### ISSUE TITLE
AttributeError: 'Flask' object has no attribute 'before_first_request'.

### ISSUE THREAD

**Issue by bezborodow** [shonenada/flask-rbac#36]
It seems that `flask_rbac` is using deprecated API. `before_first_request` is no longer supported.

```
 Traceback (most recent call last):
   File "app/uwsgi.py", line 4, in <module>
     app = create_app()
           ^^^^^^^^^^^^
   File "/opt/www/gaas-bms/app/__init__.py", line 32, in create_app
     rbac.init_app(app)
   File "/opt/www/gaas-bms/venv/lib64/python3.11/site-packages/flask_rbac/__init__.py", line 179, in init_app
     app.before_first_request(self._setup_acl)
     ^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'Flask' object has no attribute 'before_first_request'.
```

**Comment by marcamengual** [comment]
_before_first_request_ is deprecated since Flask 2.3.0 to solve this you need to change it for _before_request_ 

I dont think this Flask-RBAC will be updated.

Warining that in Flask 2.4.x will remove more deprecated code that is used in this Package.

**Comment by bezborodow** [comment]
> To solve this you need to change it for `before_request` in the code.

That is incorrect. The recommendation is to move configuration code to the setup phase of the application.

See pallets/flask/issues/4605.

**Comment by bezborodow** [comment]
> I don't think this Flask-RBAC package will be updated.

In this case, should we mark the entire package [as deprecated](https://www.dampfkraft.com/code/how-to-deprecate-a-pypi-package.html)?

**Comment by marcamengual** [comment]
> > I don't think this Flask-RBAC package will be updated.
> 
> In this case, should we mark the entire package [as deprecated](https://www.dampfkraft.com/code/how-to-deprecate-a-pypi-package.html)?

last update was a year ago, and it broke about a month ago. i would give more grace period

**Comment by jt-bg** [comment]
I ran into this issue as well. Copying Hokanosekai's code into venv worked locally for me.
